server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spider?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/mapper/**/*Mapper.xml,com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
mybatis:
  table:
    auto: update  #update: 数据表实体类只要有变动，就会对数据表实施更改操作，包括删除表、新增表、更新表字段等。
  model:
    pack: com.ongl.chen.utils.spider.beans.cbg,com.ongl.chen.utils.spider.beans  #扫描数据实体位置
  database:
    type: mysql  #数据库类型



selenuim:
  config: /Users/onglchen/proenv/selenium/config.ini
chrome:
  driver:
    path: /usr/local/bin/chromedriver

max:
  pull-down-count: 10
  item-count: 20
pull-down:
  sleep-time-millis: 3000
get-detail-url:
  sleep-time-millis: 3000
